export const FontSizes = {
  fontName: 'Arial',
  BigPriceFont: 20,
  SearchCarTitleFont: 16,
  HeadingText: 32,
  LoginSubHeading: 14,
  LabelText: 16,
  ButtonText: 20,
  CarListingPriceSize: 18,
  CarListingYearModelSize: 14,
  MainSearchImageHeight: 200,
  priceSize: 16,
  detailCategory: 24,
  detailName: 18,
  priceDetailSize: 26,
};
